### ISSUE TITLE
There is a file that parse error occurs

### ISSUE THREAD

**Issue by holyshared** [akabekobeko/npm-xlsx-extractor#12]
An error occurs when parse the xlsx file.
The contents of the error is something like the following.

```
TypeError: Cannot set property '0' of undefined
```

**Used test file**
[example.xlsx](https://github.com/akabekobeko/npm-xlsx-extractor/files/444328/example.xlsx)

**Tried code**

``` js
const XlsxExtractor = require('xlsx-extractor');
const extractor = new XlsxExtractor('./example.xlsx');

extractor.extract(1).then((results) => {
  console.log(results);
}).catch((err) => {
  console.log(err); // TypeError: Cannot set property '0' of undefined
});
```

**Enviroment**
- nodejs - v4.4.5
- npm - 2.15.5

**Comment by holyshared** [comment]
fixed a bug.
patch is [PR#13](https://github.com/akabekobeko/npm-xlsx-extractor/pull/13).

**Comment by akabekobeko** [comment]
Thanks for the report and pull request, pull request was merged.
Please check with v1.0.2.

**Comment by holyshared** [comment]
thanks!
